/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.tienda.de.refacciones.Interfaces;

import java.awt.HeadlessException;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;


import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import proyecto.tienda.de.refacciones.ArchivoClientes;
import proyecto.tienda.de.refacciones.*;
import proyecto.tienda.de.refacciones.Clases.*;


public class CobrarProd extends javax.swing.JFrame {
    DefaultTableModel m,mod;static int d;int val=0;
    static ArrayList listaLeida =new ArrayList<>();
    static float total;DefaultTableModel n;
    float subtotal,desc;
    double igv;
    
    private ImageIcon imagen;
    private Icon icono;
    
    public CobrarProd() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLocationRelativeTo(this);
        this.Imagenzs2(this.jLabel24, "src/Imagenes/IconoElim.png");
        this.Imagenzs2(this.jLabel23, "src/Imagenes/IconoSignoMas.png");
        m=(DefaultTableModel)jTablaVentas.getModel();
        jDialog1.setLocationRelativeTo(null);
        jDialog2.setLocationRelativeTo(null);
        jDialog3.setLocationRelativeTo(null);
        GpoBtones.add(GpoBtonFrec);
        GpoBtones.add(GpoBtonGen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaInv = new javax.swing.JTable();
        jAgregar = new javax.swing.JButton();
        TxtCantidad = new javax.swing.JTextField();
        jTxtCant = new javax.swing.JLabel();
        jBBUSCARPROD = new javax.swing.JToggleButton();
        jTFbuscaproductos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTTablaC2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        GpoBtonGen = new javax.swing.JRadioButton();
        GpoBtonFrec = new javax.swing.JRadioButton();
        jTFNombreC = new javax.swing.JTextField();
        jTFPaternoC = new javax.swing.JTextField();
        jTFMaternoC = new javax.swing.JTextField();
        jTFTelefonoC = new javax.swing.JTextField();
        jTFCorreoC = new javax.swing.JTextField();
        jTFFolioC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        BtonAgregarClient = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        GpoBtones = new javax.swing.ButtonGroup();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jDialog4 = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TxtImp = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TxtCamb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        TxtEf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaVentas = new javax.swing.JTable();
        BotonAgProd = new javax.swing.JButton();
        EliminarProd = new javax.swing.JToggleButton();
        jRealizarPago = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtSubTotal = new javax.swing.JTextField();
        TxtTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtDesc = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        TxtTipoCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtNombreCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtTel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtFolio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BtonNuevoCliente = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(182, 219, 246));
        jPanel3.setForeground(new java.awt.Color(182, 219, 246));

        jTablaInv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre del Producto", "No. Productos", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablaInv);
        if (jTablaInv.getColumnModel().getColumnCount() > 0) {
            jTablaInv.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        jAgregar.setText("AGREGAR");
        jAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarActionPerformed(evt);
            }
        });

        TxtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCantidad.setText("1");
        TxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCantidadActionPerformed(evt);
            }
        });

        jTxtCant.setText("Cantidad:");

        jBBUSCARPROD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBBUSCARPROD.setText("Buscar");
        jBBUSCARPROD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBUSCARPRODActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Introduzca el codigo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTxtCant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFbuscaproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBBUSCARPROD)
                        .addGap(172, 172, 172)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFbuscaproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBUSCARPROD)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCant))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jTTablaC2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Folio", "Telefono", "Tipo de Cliente"
            }
        ));
        jScrollPane4.setViewportView(jTTablaC2);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(133, 202, 193));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nuevo Cliente");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Apellido Paterno");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Apellido Materno");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Telefono");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Correo");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Folio");

        GpoBtonGen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GpoBtonGen.setText("General");
        GpoBtonGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GpoBtonGenActionPerformed(evt);
            }
        });

        GpoBtonFrec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GpoBtonFrec.setText("Frecuente");

        jTFNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreCActionPerformed(evt);
            }
        });

        jTFMaternoC.setPreferredSize(new java.awt.Dimension(6, 25));

        jTFTelefonoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTelefonoCActionPerformed(evt);
            }
        });

        jTFCorreoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCorreoCActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Tipo de Cliente");

        BtonAgregarClient.setBackground(new java.awt.Color(102, 184, 62));
        BtonAgregarClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtonAgregarClient.setText("AGREGAR");
        BtonAgregarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonAgregarClientActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTFMaternoC, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFTelefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCorreoC, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jTFFolioC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFPaternoC, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GpoBtonGen)
                            .addComponent(GpoBtonFrec))
                        .addGap(40, 40, 40))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(BtonAgregarClient, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GpoBtonFrec)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jTFPaternoC)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTFMaternoC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTFTelefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel14))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCorreoC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jTFFolioC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(BtonAgregarClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(GpoBtonGen)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jRadioButton2.setText("jRadioButton2");

        jTextField4.setText("jTextField4");

        jPanel7.setBackground(new java.awt.Color(153, 201, 229));

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel18.setText("Importe Total:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel20.setText("Efectivo Recibido:");

        TxtImp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TxtImp.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        TxtImp.setEnabled(false);
        TxtImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtImpActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("Cambio =");

        TxtCamb.setBackground(new java.awt.Color(153, 201, 229));
        TxtCamb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TxtCamb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCamb.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtCamb.setEnabled(false);
        TxtCamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCambActionPerformed(evt);
            }
        });

        jButton1.setText("FINALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("CANCELAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel22.setText("PAGO EN EFECTIVO");

        TxtEf.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        TxtEf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtEf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtEfKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel18)
                        .addGap(43, 43, 43)
                        .addComponent(TxtImp, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel22))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtCamb)
                                    .addComponent(TxtEf, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TxtImp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCamb, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel19.setText("jLabel19");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jTablaVentas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cantidad", "Nombre Articulo", "Precio Unitario", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaVentas);
        if (jTablaVentas.getColumnModel().getColumnCount() > 0) {
            jTablaVentas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTablaVentas.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTablaVentas.getColumnModel().getColumn(2).setPreferredWidth(300);
            jTablaVentas.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTablaVentas.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        BotonAgProd.setBackground(new java.awt.Color(60, 177, 41));
        BotonAgProd.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        BotonAgProd.setText("Agregar Producto");
        BotonAgProd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonAgProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgProdActionPerformed(evt);
            }
        });

        EliminarProd.setBackground(new java.awt.Color(255, 0, 0));
        EliminarProd.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        EliminarProd.setForeground(new java.awt.Color(255, 255, 255));
        EliminarProd.setText("Eliminar Producto");
        EliminarProd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProdActionPerformed(evt);
            }
        });

        jRealizarPago.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jRealizarPago.setText("Realizar Pago");
        jRealizarPago.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRealizarPagoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Barcade", 0, 48)); // NOI18N
        jLabel2.setText("Caja Registradora");

        jToggleButton4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jToggleButton4.setText("Volver al Menú Principal");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(106, 177, 202));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("SUB TOTAL");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("TOTAL:");

        TxtSubTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        TxtSubTotal.setForeground(new java.awt.Color(51, 255, 0));
        TxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSubTotal.setCaretColor(new java.awt.Color(51, 255, 0));
        TxtSubTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSubTotal.setEnabled(false);
        TxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSubTotalActionPerformed(evt);
            }
        });

        TxtTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        TxtTotal.setForeground(new java.awt.Color(51, 51, 51));
        TxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtTotal.setCaretColor(new java.awt.Color(255, 51, 51));
        TxtTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtTotal.setEnabled(false);
        TxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Descuento:");

        TxtDesc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtDesc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtDesc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtDesc.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(69, 69, 69)
                .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtSubTotal)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addComponent(TxtDesc)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(106, 177, 202));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jToggleButton3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jToggleButton3.setText("Buscar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        TxtTipoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtTipoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtTipoCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtTipoCliente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtTipoCliente.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cliente: ");

        TxtNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtNombreCliente.setForeground(new java.awt.Color(0, 51, 51));
        TxtNombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtNombreCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtNombreCliente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtNombreCliente.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Telefono:");

        TxtTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtTel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtTel.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtTel.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Folio:");

        TxtFolio.setForeground(new java.awt.Color(0, 51, 51));
        TxtFolio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtFolio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtFolio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtFolio.setEnabled(false);
        TxtFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFolioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DATOS GENERALES");

        BtonNuevoCliente.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        BtonNuevoCliente.setText("Nuevo Cliente");
        BtonNuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonNuevoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(TxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(TxtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(TxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(jToggleButton3)
                        .addGap(46, 46, 46)
                        .addComponent(BtonNuevoCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(19, 19, 19))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton3)
                            .addComponent(BtonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonAgProd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jRealizarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EliminarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton4)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAgProd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jRealizarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgProdActionPerformed
           
            
            jDialog1.setVisible(true);
            
            jDialog1.setSize(638,550);
            jDialog1.setLocationRelativeTo(null);
            mod=(DefaultTableModel)jTablaInv.getModel();
            Datos();
            
    }//GEN-LAST:event_BotonAgProdActionPerformed

    private void jAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarActionPerformed
            int filsel=jTablaInv.getSelectedRow();

        try{
            String codigo,nombre,descripcion,precio,noart,cant,importe;
            double calcula=0.0,x=0.0;
            int canti=0;
            if(filsel==-1){
                System.out.println("xd");
                JOptionPane.showMessageDialog(null, "Debe seleccionar un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
            }else{
                m=(DefaultTableModel) jTablaInv.getModel();
                codigo=jTablaInv.getValueAt(filsel, 0).toString();
                nombre=jTablaInv.getValueAt(filsel, 1).toString();
                noart=jTablaInv.getValueAt(filsel, 2).toString();
                precio=jTablaInv.getValueAt(filsel, 3).toString();
                cant=TxtCantidad.getText() ;

                if(Integer.parseInt(noart)<Integer.parseInt(cant)){
                    JOptionPane.showMessageDialog(null, "Por el momento no contamos con tal cantidad!!\nIngrese otra cantidad");
                }else{
                    x=(Double.parseDouble(precio))*(Integer.parseInt(cant));
                    importe=String.valueOf(x);
                    m=(DefaultTableModel) jTablaVentas.getModel();
                    String filaelemnto[ ] = {codigo,cant,nombre,precio,importe};
                    m.addRow(filaelemnto);
                    
                    
                    
                    
                    calcula =(Float.parseFloat(precio)* Integer.parseInt(TxtCantidad.getText()));
                    subtotal= (float) ((float)total+calcula);
                    if(TxtTipoCliente.getText().equals("Frecuente")){
                        desc=(float) (subtotal*.15);
                        TxtDesc.setText(""+desc);
                    }else{
                        desc=0;
                        TxtDesc.setText("Ninguno");
                    }
                    
                   
                    
                    total=subtotal-desc;
                    TxtTotal.setText(""+Math.round(total*100.0)/100.0);
                    TxtSubTotal.setText(""+Math.round(subtotal*100.0)/100.0);    
                    
                }
            }

        }catch(HeadlessException | NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Verifique seleccion del Produto","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jAgregarActionPerformed
   private void Calcular(){
       total=0;subtotal=0;desc=0;
       float precio,calcula;int fil;
       fil=jTablaVentas.getRowCount();
       for(int i=0;i<fil;i++){
              System.out.println("sdf"+jTablaVentas.getValueAt(i, 3));
           precio=Float.parseFloat((String)jTablaVentas.getValueAt(i, 3));
           calcula =(precio*(Integer.parseInt((String)jTablaVentas.getValueAt(i, 1))));
            if(TxtTipoCliente.getText().equals("Frecuente")){
                        desc=(float) (subtotal*.15);
                        TxtDesc.setText(""+desc);
                    }else{
                        desc=0;
                        TxtDesc.setText("Ninguno");
                    }
                    
                    total=subtotal;
                    subtotal= (float) ((float)total+calcula);
                    total=subtotal-desc;
                    TxtTotal.setText(""+Math.round(total*100.0)/100.0);
                    TxtSubTotal.setText(""+Math.round(subtotal*100.0)/100.0);         
       }
       
       
                   
       
       
   }
  private void jBAClienteActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
         int filsel=jTTablaC2.getSelectedRow();

        try{
            String nombre,folio,telefono,general;
            if(filsel==-1){
                System.out.println("xd");
                JOptionPane.showMessageDialog(null, "Debe seleccionar un Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
            }else{
                n=(DefaultTableModel) jTTablaC2.getModel();
                nombre=jTTablaC2.getValueAt(filsel, 0).toString();
                folio=jTTablaC2.getValueAt(filsel, 1).toString();
                telefono=jTTablaC2.getValueAt(filsel, 2).toString();
                general=jTTablaC2.getValueAt(filsel, 3).toString();

            }

        }catch(HeadlessException | NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Verifique seleccion del Cliente","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }          
  
      private void jBRPagoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       JFrame TablaCobroCliente = new VENTASCLIENT();
       TablaCobroCliente.setVisible (true);  
        
    }                                       
    public void Datos2(){
    DefaultTableModel n=(DefaultTableModel) jTTablaC2.getModel();
        int filas=jTTablaC2.getRowCount();
        
        for(int i=filas-1;i>=0;i--){
            n.removeRow(i);
       }
        ArrayList listaLeidaC = ArchivoClientes.leerArchivo();
      for(Cliente cliente:(ArrayList<Cliente>)listaLeidaC){
          
          n.addRow(new Object[]{cliente.getNombre(),cliente.getFolio(),cliente.getTelefono(),cliente.getGeneral()});
      
      }
    }  
    
    
    
    private void jRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRealizarPagoActionPerformed
        
        float camb;
        if(val==0){
            JOptionPane.showMessageDialog(null,"PRIMERO DEBE DE ASIGNAR UN CLIENTE!!","ERROR!!",JOptionPane.ERROR_MESSAGE);
        }else{
            
            jDialog4.setVisible(true);
            jDialog4.setSize(400,320);
            jDialog4.setLocationRelativeTo(null);
            TxtImp.setText(TxtTotal.getText());
            
       
        }  
    }//GEN-LAST:event_jRealizarPagoActionPerformed

    private void TxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalActionPerformed

    private void TxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCantidadActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
    
        jDialog2.setVisible(true);
            jDialog2.setSize(638,400);
            jDialog2.setLocationRelativeTo(null);
            
           n=(DefaultTableModel)jTTablaC2.getModel();
            Datos2();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int filsel=jTTablaC2.getSelectedRow();

        try{
            String nombre,folio,telefono,general;
            if(filsel==-1){
                
                JOptionPane.showMessageDialog(null, "Debe seleccionar un Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
            }else{
                n=(DefaultTableModel) jTTablaC2.getModel();
                nombre=jTTablaC2.getValueAt(filsel, 0).toString();
                folio=jTTablaC2.getValueAt(filsel, 1).toString();
                telefono=jTTablaC2.getValueAt(filsel, 2).toString();
                general=jTTablaC2.getValueAt(filsel, 3).toString();
                TxtTipoCliente.setText(general);
                TxtNombreCliente.setText(nombre);
                TxtTel.setText(telefono);TxtFolio.setText(folio);
                Calcular();
                val=1;
            }
            
        }catch(HeadlessException | NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Verifique seleccion del Cliente","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFolioActionPerformed
       
    }//GEN-LAST:event_TxtFolioActionPerformed

    private void BtonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonNuevoClienteActionPerformed
        jDialog3.setVisible(true);
            jDialog3.setSize(470,400);
            jDialog3.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtonNuevoClienteActionPerformed

    private void GpoBtonGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GpoBtonGenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GpoBtonGenActionPerformed

    private void jTFNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreCActionPerformed

    private void jTFTelefonoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTelefonoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTelefonoCActionPerformed

    private void BtonAgregarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonAgregarClientActionPerformed
       int N1,N2;
        ArrayList listaClientes = new ArrayList<>();
        Cliente  objc = new Cliente ();
        objc.setNombre(jTFNombreC.getText());
        objc.setApellidoPaterno(jTFPaternoC.getText());
        objc.setApellidoMaterno(jTFMaternoC.getText());
        N1=Integer.parseInt(jTFTelefonoC.getText());
        objc.setTelefono(N1);
        objc.setCorreoElectronico(jTFCorreoC.getText());
        N2=Integer.parseInt(jTFFolioC.getText());
        objc.setFolio(N2);
        if(GpoBtonFrec.isSelected()){
            objc.setGeneral("Frecuente");
        }else{
            objc.setGeneral("General");
        }
        
        listaClientes.add(objc);
        ArchivoClientes.aniadirArchivo(listaClientes);
        objc=null;
        limpiar();
    }                                        

                                             

        public void limpiar(){
        jTFNombreC.setText("");
        jTFPaternoC.setText("");
        jTFMaternoC.setText("");
        jTFTelefonoC.setText("");
        jTFCorreoC.setText("");
        jTFFolioC.setText("");
        GpoBtones.clearSelection();
    }//GEN-LAST:event_BtonAgregarClientActionPerformed

    private void jBBUSCARPRODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBUSCARPRODActionPerformed
        // TODO add your handling code here:
        TableRowSorter trsfiltro = new TableRowSorter(jTablaInv.getModel());
        jTablaInv.setRowSorter(trsfiltro);
        trsfiltro.setRowFilter(RowFilter.regexFilter(jTFbuscaproductos.getText(),0));
    }//GEN-LAST:event_jBBUSCARPRODActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        MenuPrincipalVend ME=new MenuPrincipalVend();
        ME.setVisible(true);this.setVisible(false);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jTFCorreoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCorreoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCorreoCActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jDialog3.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProdActionPerformed
        int resp,fsel;float aux;
        fsel=jTablaVentas.getSelectedRow();
        if(fsel== -1){
        
         JOptionPane.showMessageDialog(null, "Selecione una fila ","Error",JOptionPane.WARNING_MESSAGE);
        }
        else {
            resp=JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar este producto?","Elminar",
                        JOptionPane.YES_NO_OPTION);
            
            if(resp==JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null, " Fila eliminada  ");
                aux=subtotal;
                aux=aux-(Float.parseFloat((String)jTablaVentas.getValueAt(fsel, 4)))  ;
                m.removeRow(jTablaVentas.getSelectedRow());
                
                    TxtSubTotal.setText(""+Math.round(aux*100.0)/100.0);  
                if(TxtTipoCliente.getText().equals("Frecuente")){
                    desc=(float) (aux*.15);
                    TxtDesc.setText(""+desc);
                }
                total=aux-desc;
                TxtTotal.setText(""+Math.round(total*100.0)/100.0);
                   
            }
                
        }        
    }//GEN-LAST:event_EliminarProdActionPerformed

    private void TxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSubTotalActionPerformed

    private void TxtCambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCambActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCambActionPerformed

    private void TxtImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtImpActionPerformed
        
    }//GEN-LAST:event_TxtImpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Producto prodvend=new Producto();int no,cod;
//        Lineas para guardar numero de articulos que se venden
            listaLeida = ArchivoProducto.leerArchivo();
            for(Producto prod:(ArrayList<Producto>)listaLeida){
                for(int i=0;i<jTablaVentas.getRowCount();i++){
                
                
                if(prod.getDescripcion().equals((String)jTablaVentas.getValueAt(i, 2))){
                    
                    no=(Integer.parseInt((String)jTablaVentas.getValueAt(i, 1)));
                    cod=(Integer.parseInt((String)jTablaVentas.getValueAt(i, 0)));
                    
                    ArchivoArticulosVend.Modificar(no, cod);
                    ArchivoProducto.Modificardat(cod,no);
                   
                }
            }
        }//Fin
            
            
            Guardardatos();
            
            
            TxtTipoCliente.setText("");
            TxtNombreCliente.setText("");TxtTel.setText("");TxtFolio.setText("");
            DefaultTableModel m=(DefaultTableModel) jTablaVentas.getModel();
            int filas=jTablaVentas.getRowCount();
        
            for(int i=filas-1;i>=0;i--){
                m.removeRow(i);
            }
            
            jDialog4.setVisible(false);
            TxtTotal.setText("");
            TxtSubTotal.setText("");
            TxtDesc.setText("");
            }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        jDialog4.setVisible(false);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void TxtEfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEfKeyReleased
        float camb;
        camb=(Float.parseFloat(TxtEf.getText())-Float.parseFloat(TxtTotal.getText()));
           TxtCamb.setText(""+camb);
    }//GEN-LAST:event_TxtEfKeyReleased


    public void Datos(){
       
       DefaultTableModel mod=(DefaultTableModel) jTablaInv.getModel();
        int filas=jTablaInv.getRowCount();
        
        for(int i=filas-1;i>=0;i--){
            mod.removeRow(i);
       }
      listaLeida = ArchivoProducto.leerArchivo();
      for(Producto producto:(ArrayList<Producto>)listaLeida){
          
          mod.addRow(new Object[]{producto.getCodigo(),producto.getDescripcion(),producto.getNoArticulos(), 
          producto.getPrecio()});
      
      }
      
    }
   
    public void Guardardatos(){
        ArrayList listaprod=new  ArrayList();
        TicketDCompra tick=new TicketDCompra();
        float calcula,precio;
       
        for(int i=0;i<jTablaVentas.getRowCount();i++){
           tick.setFolio(Integer.parseInt(TxtFolio.getText().trim()));
           tick.setNumeroArt(Integer.parseInt((String)jTablaVentas.getValueAt(i, 1)) );
           tick.setArticulos((String)jTablaVentas.getValueAt(i, 2));
           precio=(float) jTablaInv.getValueAt(i, 3);
           calcula =tick.getNumeroArt() * precio;
           tick.setTotal(calcula);
           listaprod.add(tick);
           ArchivoProdTicket.aniadirArchivo(listaprod);
           listaprod=new ArrayList();
        }
        
        
    }
    
    
   private void Imagenzs2(JLabel jLabel2,String ruta){
        this.imagen =new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(), Image.SCALE_DEFAULT));
        jLabel2.setIcon(this.icono);
        this.repaint();
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CobrarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CobrarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CobrarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CobrarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CobrarProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgProd;
    private javax.swing.JButton BtonAgregarClient;
    private javax.swing.JButton BtonNuevoCliente;
    private javax.swing.JToggleButton EliminarProd;
    private javax.swing.JRadioButton GpoBtonFrec;
    private javax.swing.JRadioButton GpoBtonGen;
    private javax.swing.ButtonGroup GpoBtones;
    private javax.swing.JTextField TxtCamb;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtDesc;
    private javax.swing.JTextField TxtEf;
    private javax.swing.JTextField TxtFolio;
    private javax.swing.JTextField TxtImp;
    private javax.swing.JTextField TxtNombreCliente;
    private javax.swing.JTextField TxtSubTotal;
    private javax.swing.JTextField TxtTel;
    private javax.swing.JTextField TxtTipoCliente;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JButton jAgregar;
    private javax.swing.JToggleButton jBBUSCARPROD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JToggleButton jRealizarPago;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTFCorreoC;
    private javax.swing.JTextField jTFFolioC;
    private javax.swing.JTextField jTFMaternoC;
    private javax.swing.JTextField jTFNombreC;
    private javax.swing.JTextField jTFPaternoC;
    private javax.swing.JTextField jTFTelefonoC;
    private javax.swing.JTextField jTFbuscaproductos;
    private javax.swing.JTable jTTablaC2;
    private javax.swing.JTable jTablaInv;
    private javax.swing.JTable jTablaVentas;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel jTxtCant;
    // End of variables declaration//GEN-END:variables
}
